name: passgen
description: "A password generator app than uses linear permutation, permutation with repeating elements, and truncated elements to generate passwords."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#009FE3"
  image: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
